In [1]:
import numpy as np

In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a[0,2]

3

In [11]:
# Slicing
a[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a[:4]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a.shape

(3, 3)

In [16]:
np.sum(a)

45

In [19]:
np.max(a)


9

In [18]:
np.min(a)

1

In [20]:
np.mean(a)

5.0

In [21]:
np.std(a)

2.581988897471611

In [23]:
np.add(a,a)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [24]:
np.dot(a,a)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [25]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
for i in np.nditer(b):
    print(i,end=' ')

1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 